-- Run these SQL commands in Snowflake as ACCOUNTADMIN user
-- Copy and paste into Snowflake web console

-- 1. CREATE DATABASE
CREATE DATABASE IF NOT EXISTS BAIN_ANALYTICS;

-- 2. CREATE SCHEMAS
CREATE SCHEMA IF NOT EXISTS BAIN_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS BAIN_ANALYTICS.DEV;
CREATE SCHEMA IF NOT EXISTS BAIN_ANALYTICS.PROD;

-- 3. CREATE WAREHOUSE
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- 4. Verify everything was created
SHOW DATABASES LIKE 'BAIN_ANALYTICS';
SHOW SCHEMAS IN DATABASE BAIN_ANALYTICS;
SHOW WAREHOUSES LIKE 'COMPUTE_WH';

-- That's it! Once these are created, you can run: bash RUN_NOW.sh
